# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(help_text='Enter a brief description about profession or educational background', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(blank=True, default=100, editable=False, null=True),
        ),
    ]
