# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171116_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
