# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 03:32
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
