# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 04:36
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171117_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+880', max_length=128),
        ),
    ]
