# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 05:10
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171117_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
