# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171117_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(help_text='Enter a brief description about profession or educational background', max_length=400),
        ),
    ]
