# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171118_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Profile', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='course',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='motivation',
            field=models.TextField(help_text='Enter a brief description about the course', max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='motivation',
            field=models.TextField(help_text='Enter a brief description about the lesson', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(help_text='Enter a brief description about profession or educational background', max_length=300),
        ),
    ]
