# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
