# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('wiew_course_lessons', 'View course lessons'),), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
