# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180115_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='motivation',
            field=models.TextField(help_text='Enter a brief description about the course', max_length=1000),
        ),
    ]
