# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
