# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRequest',
            new_name='Course_request',
        ),
        migrations.RenameModel(
            old_name='InstructorFollow',
            new_name='Follow',
        ),
    ]
