# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_auto_20180118_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
