# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180120_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
