# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180120_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_request',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Course_request',
        ),
    ]
